services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5200:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Notes-App
      - PORT=5000
      - NODE_ENV=development
    volumes:
      - ./api:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

